# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btn1 = QtWidgets.QPushButton(self.centralwidget)
        self.btn1.setGeometry(QtCore.QRect(120, 320, 75, 23))
        self.btn1.setObjectName("btn1")
        self.code = QtWidgets.QLineEdit(self.centralwidget)
        self.code.setGeometry(QtCore.QRect(20, 190, 281, 31))
        self.code.setAlignment(QtCore.Qt.AlignCenter)
        self.code.setObjectName("code")
        self.code_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.code_2.setGeometry(QtCore.QRect(20, 250, 281, 31))
        self.code_2.setAlignment(QtCore.Qt.AlignCenter)
        self.code_2.setObjectName("code_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(150, 130, 31, 16))
        self.label.setObjectName("label")
        self.code_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.code_3.setGeometry(QtCore.QRect(490, 190, 281, 31))
        self.code_3.setAccessibleDescription("")
        self.code_3.setAutoFillBackground(False)
        self.code_3.setInputMask("")
        self.code_3.setText("")
        self.code_3.setAlignment(QtCore.Qt.AlignCenter)
        self.code_3.setReadOnly(False)
        self.code_3.setObjectName("code_3")
        self.code_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.code_4.setGeometry(QtCore.QRect(490, 250, 281, 31))
        self.code_4.setInputMask("")
        self.code_4.setText("")
        self.code_4.setAlignment(QtCore.Qt.AlignCenter)
        self.code_4.setObjectName("code_4")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(610, 130, 41, 16))
        self.label_2.setObjectName("label_2")
        self.btn1_2 = QtWidgets.QPushButton(self.centralwidget)
        self.btn1_2.setGeometry(QtCore.QRect(590, 380, 75, 23))
        self.btn1_2.setAutoFillBackground(False)
        self.btn1_2.setObjectName("btn1_2")
        self.code_5 = QtWidgets.QLineEdit(self.centralwidget)
        self.code_5.setGeometry(QtCore.QRect(490, 310, 281, 31))
        self.code_5.setInputMask("")
        self.code_5.setText("")
        self.code_5.setAlignment(QtCore.Qt.AlignCenter)
        self.code_5.setObjectName("code_5")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "SuperVisor"))
        self.btn1.setText(_translate("MainWindow", "Login"))
        self.code.setPlaceholderText(_translate("MainWindow", "Username"))
        self.code_2.setPlaceholderText(_translate("MainWindow", "Password"))
        self.label.setText(_translate("MainWindow", "Login"))
        self.code_3.setPlaceholderText(_translate("MainWindow", "Username"))
        self.code_4.setPlaceholderText(_translate("MainWindow", "Password"))
        self.label_2.setText(_translate("MainWindow", "Register"))
        self.btn1_2.setText(_translate("MainWindow", "Register"))
        self.code_5.setPlaceholderText(_translate("MainWindow", "Email"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
