# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'webCam.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1024, 860)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.imgLabel = QtWidgets.QLabel(self.centralwidget)
        self.imgLabel.setGeometry(QtCore.QRect(0, 0, 1024, 860))
        self.imgLabel.setFrameShape(QtWidgets.QFrame.Panel)
        self.imgLabel.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.imgLabel.setLineWidth(1)
        self.imgLabel.setMidLineWidth(0)
        self.imgLabel.setText("")
        self.imgLabel.setObjectName("imgLabel")
        self.btn_leave = QtWidgets.QPushButton(self.centralwidget)
        self.btn_leave.setGeometry(QtCore.QRect(910, 720, 75, 23))
        self.btn_leave.setFlat(False)
        self.btn_leave.setObjectName("btn_leave")
        self.btn_enable = QtWidgets.QPushButton(self.centralwidget)
        self.btn_enable.setGeometry(QtCore.QRect(0, 0, 75, 23))
        self.btn_enable.setFlat(False)
        self.btn_enable.setObjectName("btn_enable")
        self.btn_disable = QtWidgets.QPushButton(self.centralwidget)
        self.btn_disable.setGeometry(QtCore.QRect(70, 0, 75, 23))
        self.btn_disable.setAutoDefault(False)
        self.btn_disable.setDefault(False)
        self.btn_disable.setFlat(False)
        self.btn_disable.setObjectName("btn_disable")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "SuperVisor"))
        self.btn_leave.setText(_translate("MainWindow", "Leave"))
        self.btn_enable.setText(_translate("MainWindow", "Enable"))
        self.btn_disable.setText(_translate("MainWindow", "Disable"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
